# Generated by Django 3.2.3 on 2021-05-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudrest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='img',
        ),
    ]
